# Generated by Django 3.2.7 on 2021-09-09 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='DEADLINE')),
                ('note', models.TextField(blank=True, verbose_name='TASK')),
                ('member', models.CharField(blank=True, max_length=15, verbose_name='STAFF')),
                ('prog', models.CharField(choices=[('DONE!!!', 'DONE!!!'), ('Started', 'Started'), (' ', ' ')], default='0', max_length=10)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production', verbose_name='PLOJECT')),
            ],
        ),
    ]
