# Generated by Django 3.2.7 on 2021-09-09 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='PLOJECT')),
            ],
            options={
                'verbose_name': 'PLOJECT',
                'verbose_name_plural': 'PLOJECT',
            },
        ),
        migrations.CreateModel(
            name='ProdUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='OWNER')),
                ('is_editor', models.BooleanField(default=False, verbose_name='EDITER')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production', verbose_name='PLOJECT')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='STAFF')),
            ],
            options={
                'verbose_name': 'STAFF',
                'verbose_name_plural': 'STAFF',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_dt', models.DateTimeField(verbose_name='期限')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL, verbose_name='招待される人')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL, verbose_name='招待する人')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.production', verbose_name='PLOJECT')),
            ],
            options={
                'verbose_name': 'PLOJECTへの招待',
                'verbose_name_plural': 'PLOJECTへの招待',
                'ordering': ['exp_dt'],
            },
        ),
    ]
